### ISSUE TITLE
LVOSV2 test server

### ISSUE THREAD

**Issue by yahooo-m** [LingyiHongfd/LVOS#6] opened 2024-05-09 03:31 UTC
How can I test the LVOSV2 test set?

**Comment by LingyiHongfd** [comment] 2024-05-09 04:00
Hello, thanks for your interest. We haven't had the plan to release the LVOS V2 test server. We will release the code for evaluation of valid set within this week. For the LVOS V2 test set, we will keep it for the challenge purpose. You can evaluate the ability of your model by using the validation set. 
Feel free to contact me or raise the issue if you have any question.

Bests,
Lingyi

**Comment by yahooo-m** [comment] 2024-05-09 04:57
Thanks! Could the evaluation code of v1 be used to validate the v2?

**Comment by LingyiHongfd** [comment] 2024-05-09 05:05
Indeed, the evaluation code for v2 is similar to that of v1 for semi-supervised vos. However, due to the unseen video list is loaded through txt file, if you don't have the txt file for v2, you can not evaluate your model correctly. Besides, we also optimize the code to speed up the evaluation process. 

Bests,
Lingyi

**Comment by yahooo-m** [comment] 2024-05-09 05:09
Looking forward to it!
Best,
MDS

**Comment by yahooo-m** [comment] 2024-05-09 05:11
By the way, when will you release the code of Onetracker? I am also interested~

**Comment by LingyiHongfd** [comment] 2024-05-09 05:27
Sry, we don't have the plan to release the code of OneTracker. The code of OneTracker is extremely simple. I think you can reproduce it based on ViPT easily.  If you have any question about OneTracker, feel free to contact me through email, and you can find my email from my homepage or the paper of OneTracker. Thanks for your interest on our works!

**Comment by LingyiHongfd** [comment] 2024-05-10 06:13
Hi, we have released the evaluation code for LVOS V2, and you can find it at [here](https://github.com/LingyiHongfd/lvos-evaluation). You can set the `lvos_path` to switch the evaluation for v1 or v2. Please see this repo for more details. 
If you have any question, feel free to let me know.

Best regards,
Lingyi

**Comment by LingyiHongfd** [comment] 2024-05-20 03:52
I will close it for now. Feel free to open it in case of future questions!

**Closed as completed by LingyiHongfd** 2024-05-20 03:52 UTC
